In [1]:
import numpy as np

In [4]:
c = np.array ([[1,-1],[6, 4]])
c

array([[ 1, -1],
       [ 6,  4]])

In [5]:
#determinan
np.linalg.det(c)


9.999999999999998

In [7]:
#eigendocomposition
np.linalg.eig(c)

(array([2.5+1.93649167j, 2.5-1.93649167j]),
 array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
        [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]]))

In [8]:
#eigval(eigen value) & eigen vecs (eigen vector)
eigvals,eigvecs = np.linalg.eig(c)


In [9]:
eigvals

array([2.5+1.93649167j, 2.5-1.93649167j])

In [10]:
eigvecs

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

jadi [1,3] bukan merupakan eigval dari C